/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-13 10:02:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class review_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/admin/footer.jsp", Long.valueOf(1680537041998L));
    _jspx_dependants.put("/admin/header.jsp", Long.valueOf(1681109934211L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1679496033882L));
    _jspx_dependants.put("jar:file:/D:/BookStoreWebsite/BookStoreProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStoreWebsite/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Update Review</title>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta name='viewport' content='width=device-width, initial-scale=1'>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.richtext.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\"  media=\"all\"/>\r\n");
      out.write("<link rel='stylesheet' type='text/css' media='screen' href='../bootstrap/bootstrap.css'>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	   \r\n");
      out.write("	");
      out.write("<div align=\"center\" class=\"col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12\">\r\n");
      out.write("     <div >\r\n");
      out.write("          <a href=\"./\"><img src=\"/BookStoreWebsite/images/BookstoreAdminLogo.png\" /></a>    \r\n");
      out.write("     </div>    \r\n");
      out.write("    \r\n");
      out.write("   <div>\r\n");
      out.write("         Welcome, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" | <a href=\"logout\">Logout</a>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("       <br>\r\n");
      out.write("   <div id=\"head\">\r\n");
      out.write("       <div class=\"logo\">\r\n");
      out.write("           <a href=\"./\">\r\n");
      out.write("	         <img class=\"image\" src=\"/BookStoreWebsite/images/home.png\"/><br>Home\r\n");
      out.write("	       </a>\r\n");
      out.write("	   </div>\r\n");
      out.write("	   <div class=\"logo\">\r\n");
      out.write("	       <a href=\"list_users\">\r\n");
      out.write("	         <img class=\"image\"  src=\"/BookStoreWebsite/images/user.png\"/><br>Users\r\n");
      out.write("	       </a>\r\n");
      out.write("	   </div>\r\n");
      out.write("	   <div class=\"logo\" >\r\n");
      out.write("	       <a href=\"list_category\">\r\n");
      out.write("	         <img class=\"image\"  src=\"/BookStoreWebsite/images/category.png\"/><br>Categories\r\n");
      out.write("	       </a>\r\n");
      out.write("	   </div>\r\n");
      out.write("	   <div class=\"logo\">\r\n");
      out.write("	       <a href=\"list_book\">\r\n");
      out.write("	         <img class=\"image\" src=\"/BookStoreWebsite/images/book.png\"/><br>Books\r\n");
      out.write("	       </a>\r\n");
      out.write("	   </div>\r\n");
      out.write("	   <div class=\"logo\">\r\n");
      out.write("	       <a href=\"list_customer\">\r\n");
      out.write("	         <img class=\"image\"  src=\"/BookStoreWebsite/images/customer.png\"/><br>Customers\r\n");
      out.write("	       </a>\r\n");
      out.write("	   </div>\r\n");
      out.write("	   <div class=\"logo\">\r\n");
      out.write("	       <a href=\"list_review\">\r\n");
      out.write("	         <img class=\"image\"  src=\"/BookStoreWebsite/images/review.png\"/><br>Reviews\r\n");
      out.write("	       </a>\r\n");
      out.write("	   </div>\r\n");
      out.write("	   <div class=\"logo\">\r\n");
      out.write("	       <a href=\"list_order\">\r\n");
      out.write("	          <img class=\"image\" src=\"/BookStoreWebsite/images/order.png\"/><br>Orders\r\n");
      out.write("	       </a>\r\n");
      out.write("	   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container-fluid col-md-12\" style=\"height:15px\"></div>\r\n");
      out.write("\r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("			<h2 class=\"pageheading\">Edit Review</h2>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("			<form class=\"form-horizontal\" action=\"update_review?reviewId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.reviewId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"post\" id=\"reviewform\">\r\n");
      out.write("	  <div class=\"form-group\">\r\n");
      out.write("	    <label class=\"control-label col-sm-4\" for=\"book\">Book:</label>\r\n");
      out.write("	    <div class=\"col-sm-4 col-md-4\">\r\n");
      out.write("	      <input type=\"text\" class=\"form-control\" id=\"book\" name=\"book\" placeholder=\"Enter Book\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.book.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <div class=\"form-group\">\r\n");
      out.write("	    <label class=\"control-label col-sm-4\" for=\"rating\">Rating:</label>\r\n");
      out.write("	    <div class=\"col-sm-3 col-md-4\">\r\n");
      out.write("	      <input type=\"text\" class=\"form-control\" id=\"rating\" name=\"rating\" placeholder=\"Enter rating\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.rating}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	    <div class=\"form-group\">\r\n");
      out.write("	    <label class=\"control-label col-sm-4\" for=\"customer\">Customer:</label>\r\n");
      out.write("	    <div class=\"col-sm-3 col-md-4\">\r\n");
      out.write("	      <input type=\"text\" class=\"form-control\" name=\"customer\" id=\"customer\" placeholder=\"Enter customer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.customer.fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <div class=\"form-group\">\r\n");
      out.write("	    <label class=\"control-label col-sm-4\" for=\"headline\">Headline:</label>\r\n");
      out.write("	    <div class=\"col-sm-3 col-md-4\">\r\n");
      out.write("	      <input type=\"text\" class=\"form-control\" id=\"headline\" name=\"headline\" placeholder=\"Enter headline\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.headline}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <div class=\"form-group\">\r\n");
      out.write("	    <label class=\"control-label col-sm-4\" for=\"comment\">Comment:</label>\r\n");
      out.write("	    <div class=\"col-sm-3 col-md-4\">\r\n");
      out.write("	      <textarea class=\"form-control\" id=\"comment\" name=\"comment\" placeholder=\"Enter Comment\" rows=\"3\" cols=\"20\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${review.comment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <div class=\"form-group\">\r\n");
      out.write("	    <div class=\"col-sm-offset-4 col-sm-4\">\r\n");
      out.write("	      <button type=\"submit\" class=\"btn btn-primary\">Update</button>&emsp;\r\n");
      out.write("	      <button type=\"button\" class=\"btn btn-danger\" id=\"buttoncancel\">Cancel</button>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("<div class=\"col-md-12\" align=\"center\">\r\n");
      out.write("    <div>\r\n");
      out.write("		<h4>Bookstore Administration</h4>\r\n");
      out.write("		<h4>Copyright &copy; 2023 by Evergreen Book Co., Ltd.</h4>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("		$(\"#reviewform\").validate({\r\n");
      out.write("\r\n");
      out.write("			rules : {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				comment : \"required\",\r\n");
      out.write("\r\n");
      out.write("				headline : \"required\",\r\n");
      out.write("\r\n");
      out.write("			},\r\n");
      out.write("\r\n");
      out.write("			messages : {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				fullname : \"Please enter headline\",\r\n");
      out.write("\r\n");
      out.write("				password : \"Please enter comment\"\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$(\"#buttoncancel\").click(function(){\r\n");
      out.write("			history.go(-1);\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
